{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fontawesome
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fontawesome_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fontawesome/fontawesome_{{ version }}.tar.gz
  sha256: f4ebbbe2ee8d2e2c0342b72095cfe668bd9800ea6c4bf7180300544bde7e566c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-htmltools >=0.5.1.1
    - r-rlang >=0.4.10
  run:
    - r-base
    - r-htmltools >=0.5.1.1
    - r-rlang >=0.4.10

test:
  commands:
    - $R -e "library('fontawesome')"           # [not win]
    - "\"%R%\" -e \"library('fontawesome')\""  # [win]

about:
  home: https://github.com/rstudio/fontawesome
  license: MIT
  summary: Easily and flexibly insert 'Font Awesome' icons into 'R Markdown' documents and 'Shiny' apps. These icons can be inserted into HTML content through inline 'SVG' tags or 'i' tags. There is also a utility function for exporting 'Font Awesome' icons as 'PNG' images for those situations where raster graphics are needed.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
